AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ac Rust Api
  Sample SAM Template for ac-rust-api
Resources:
  ACRustApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: ['cloudwatch:*', 'logs:*']
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: lambdaRoleAPIG
      RoleName: ACRustApiExecutionRole

  ACRustApiFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: target/lambda/release/ac-rust-lambda.zip
      Handler: doesnt.matter
      Runtime: provided
      MemorySize: 256
      Timeout: 25
      Role: !GetAtt ["ACRustApiFunctionRole", "Arn"]
      Events:
        WatchsonApiTime:
          Type: Api
          Properties:
            Path: /api/echo/{name}
            Method: GET
